### ISSUE TITLE
Couldn't start client Yang Language Server

### ISSUE THREAD

**Issue by p-montero** [theia-ide/yang-vscode#12]
Issue Type: <b>Bug</b>
Extension: Yang VS Code Extension

`Couldn't start client Yang Language Server`

[Error - 1:26:26 PM] Starting client failed
`Launching server using command /Users/pmontero/.vscode/extensions/typefox.yang-vscode-1.7.0/build/yang-language-server/bin/yang-language-server failed.`

From the developers tools:

/Users/pmontero/.vscode/extensions/typefox.yang-vscode-1.7.0/build/yang-language-server/bin/yang-language-server ENOENT: Error: spawn /Users/pmontero/.vscode/extensions/typefox.yang-vscode-1.7.0/build/yang-language-server/bin/yang-language-server ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:243 [Extension Host] rejected promise not handled within 1 second: Launching server using command /Users/pmontero/.vscode/extensions/typefox.yang-vscode-1.7.0/build/yang-language-server/bin/yang-language-server failed.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:243
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1521   ERR Launching server using command /Users/pmontero/.vscode/extensions/typefox.yang-vscode-1.7.0/build/yang-language-server/bin/yang-language-server failed.

Extension version: 1.7.0
VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:35:11.314Z)
OS version: Darwin x64 17.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by p-montero** [comment]
from VSCode > Output > Log (Window)

```
[2019-10-11 14:27:37.454] [renderer1] [error] spawn /Users/pmontero/.vscode/extensions/typefox.yang-vscode-1.7.0/build/yang-language-server/bin/yang-language-server ENOENT: Error: spawn /Users/pmontero/.vscode/extensions/typefox.yang-vscode-1.7.0/build/yang-language-server/bin/yang-language-server ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
	at onErrorNT (internal/child_process.js:407:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
[2019-10-11 14:27:38.421] [renderer1] [error] Launching server using command /Users/pmontero/.vscode/extensions/typefox.yang-vscode-1.7.0/build/yang-language-server/bin/yang-language-server failed.
```

**Comment by p-montero** [comment]
Any idea here?

**Comment by jbl241987** [comment]
Anyone know solution to this problem?

**Comment by visstro** [comment]
Also failing to start.

```
2022-11-10 02:12:07.065 [error] Error: Internal error.
	at /home/vistro/.vscode-server/extensions/typefox.yang-vscode-2.2.0/extension/pack/extension.js:1:167891
	at /home/vistro/.vscode-server/extensions/typefox.yang-vscode-2.2.0/extension/pack/extension.js:1:168185
	at Immediate.<anonymous> (/home/vistro/.vscode-server/extensions/typefox.yang-vscode-2.2.0/extension/pack/extension.js:1:168548)
	at processImmediate (node:internal/timers:466:21)
2022-11-10 02:12:07.067 [error] Error: write after end
	at new NodeError (node:internal/errors:371:5)
	at _write (node:internal/streams/writable:319:11)
	at Socket.Writable.write (node:internal/streams/writable:334:10)
	at /home/vistro/.vscode-server/extensions/typefox.yang-vscode-2.2.0/extension/pack/extension.js:1:149407
	at new Promise (<anonymous>)
	at u.write (/home/vistro/.vscode-server/extensions/typefox.yang-vscode-2.2.0/extension/pack/extension.js:1:149326)
	at m.doWrite (/home/vistro/.vscode-server/extensions/typefox.yang-vscode-2.2.0/extension/pack/extension.js:1:157751)
	at /home/vistro/.vscode-server/extensions/typefox.yang-vscode-2.2.0/extension/pack/extension.js:1:157650
```

**Comment by dhuebner** [comment]
@p-montero 
Do you have Java 11 installed?

**Comment by lingjshi** [comment]
Hi @dhuebner , I also encountered this issue, and I have double-checked that I have Java 11 installed. 

Any ideas about this issue, thank you!

Here are some info about my environment:
-----------------------------------------------------
lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterprise
Description:    Red Hat Enterprise Linux release 8.8 (Ootpa)
Release:        8.8
Codename:       Ootpa
-----------------------------------------------------
java --version
openjdk 11.0.19 2023-04-18 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.19.0.7-2) (build 11.0.19+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.19.0.7-2) (build 11.0.19+7-LTS, mixed mode, sharing)
