### ISSUE TITLE
Does not start in VSCode & MacOs-BigSur

### ISSUE THREAD

**Issue by savkin256** [theia-ide/yang-vscode#41]
Cannot start Yangster in freshly installed VSCode on BigSur: getting "Server initialization failed" Internal Error with Code -32603

Persist with JDK 8 & 11 as well

Jun 04, 2021 5:54:11 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.IllegalArgumentException: Bad escape
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Bad escape
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:607)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at io.typefox.yang.settings.PreferenceValuesProvider.createPreferenceValues(PreferenceValuesProvider.java:110)
	at io.typefox.yang.ide.server.YangExclusionProvider.getPreferences(YangExclusionProvider.java:60)
	at io.typefox.yang.ide.server.YangExclusionProvider.isExcluded(YangExclusionProvider.java:24)
	at io.typefox.yang.ide.server.YangProjectManager.lambda$newBuildRequest$0(YangProjectManager.java:27)
	at org.eclipse.xtext.xbase.lib.internal.BooleanFunctionDelegate.apply(BooleanFunctionDelegate.java:41)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:637)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators.addAll(Iterators.java:355)
	at com.google.common.collect.Lists.newArrayList(Lists.java:143)
	at com.google.common.collect.Lists.newArrayList(Lists.java:130)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toList(IterableExtensions.java:620)
	at io.typefox.yang.ide.server.YangProjectManager.newBuildRequest(YangProjectManager.java:30)
	at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:104)
	at org.eclipse.xtext.ide.server.ProjectManager.doInitialBuild(ProjectManager.java:96)
	at org.eclipse.xtext.ide.server.BuildManager.doInitialBuild(BuildManager.java:172)
	at org.eclipse.xtext.ide.server.WorkspaceManager.refreshWorkspaceConfig(WorkspaceManager.java:172)
	at org.eclipse.xtext.ide.server.WorkspaceManager.initialize(WorkspaceManager.java:145)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$initialize$0(LanguageServerImpl.java:220)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:38)
	... 5 more

[Error - 5:54:11 PM] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Bad escape
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:607)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at io.typefox.yang.settings.PreferenceValuesProvider.createPreferenceValues(PreferenceValuesProvider.java:110)
	at io.typefox.yang.ide.server.YangExclusionProvider.getPreferences(YangExclusionProvider.java:60)
	at io.typefox.yang.ide.server.YangExclusionProvider.isExcluded(YangExclusionProvider.java:24)
	at io.typefox.yang.ide.server.YangProjectManager.lambda$newBuildRequest$0(YangProjectManager.java:27)
	at org.eclipse.xtext.xbase.lib.internal.BooleanFunctionDelegate.apply(BooleanFunctionDelegate.java:41)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:637)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators.addAll(Iterators.java:355)
	at com.google.common.collect.Lists.newArrayList(Lists.java:143)
	at com.google.common.collect.Lists.newArrayList(Lists.java:130)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toList(IterableExtensions.java:620)
	at io.typefox.yang.ide.server.YangProjectManager.newBuildRequest(YangProjectManager.java:30)
	at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:104)
	at org.eclipse.xtext.ide.server.ProjectManager.doInitialBuild(ProjectManager.java:96)
	at org.eclipse.xtext.ide.server.BuildManager.doInitialBuild(BuildManager.java:172)
	at org.eclipse.xtext.ide.server.WorkspaceManager.refreshWorkspaceConfig(WorkspaceManager.java:172)
	at org.eclipse.xtext.ide.server.WorkspaceManager.initialize(WorkspaceManager.java:145)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$initialize$0(LanguageServerImpl.java:220)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:38)
	... 5 more

**Comment by dhuebner** [comment]
@savkin256 
Could you please try with the lates Yangster version 2.2.0?
You will need to have Java 11 or higher installed
