### ISSUE TITLE
Java based code helper uses 100%+ CPU

### ISSUE THREAD

**Issue by marksutherland** [theia-ide/yang-vscode#9]
Issue Type: <b>Performance Issue</b>

This occurs as soon as I open some yang files with java installed. Killing the java process doesn't help as something is watching for it and restarts it. My laptop is sitting with the fan running on high, even though nothing is happening.

Extension version: 1.7.0
VS Code version: Code 1.28.1 (3368db6750222d319c851f6d90eb619d886e08f5, 2018-10-11T18:07:48.477Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_12606469|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   23	    98	 34144	code main
    2	    49	 34145	   gpu-process
    4	   246	 34146	   window (nonFtCusTypes.yang — Untitled (Workspace))
    0	    98	 34232	     extensionHost
    0	    82	 34409	       electron_node j.js 
    0	    16	 34418	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=34232
    0	    33	 34450	       electron_node server.js 
    0	    16	 34236	     watcherService
    0	   147	 34147	   window (Vagrantfile — Repositories)
    0	     0	 34217	     /usr/local/bin/bash -l
    0	   164	 34235	     extensionHost
    0	    16	 34511	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=34235
    0	    33	 34530	       electron_node server.js 
   98	   770	 36978	       electron_node j.js 
    0	    33	 34238	     watcherService
    3	    82	 34285	   shared-process
   63	    82	 37013	   window (Issue Reporter)
    0	     0	 37014	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Vagrantfile — Repositories)
|  Window (some.yang — Untitled (Workspace))
|    Folder (1810_yang): 765 files
|      File types: yang(697) txt(35) xml(11) sh(4) md(3) tree(2) yml(1) py(1)
|                  gitreview(1) gitmodules(1)
|      Conf files:
|    Folder (Repositories): more than 24280 files
|      File types: py(9596) pyc(6899) h(1018) yml(939) so(564) txt(502)
|                  j2(403) yang(388) vim(355) json(205)
|      Conf files: makefile(15) settings.json(2) project.json(1)
|    Folder (another): 4402 files
|      File types: pyc(1912) py(1643) h(181) txt(89) so(83) yang(77) json(28)
|                  rst(27) xsl(18) pxd(16)
|      Conf files: settings.json(1) makefile(1);
```

</details>

**Comment by marksutherland** [comment]
After a full restart, this fixed itself, so I guess it got stuck in a loop when I added folders to the workspace or something? Either way, it's not an ongoing issue.

**Comment by marksutherland** [comment]
There's maybe a 50% chance of this plugin working or getting stuck and pegging a cpu at 100% with the java process. When it works it's great, but I can't figure out how to unstick and I can't see anything that would be triggering if it works or not. The output just lists the files it's validating and the features don't work.

FWIW, I'm running java 11 but I notice the README is recommending java 8. Is that likely to be an issue?

**Comment by marksutherland** [comment]
Here is a jstack dump for a stuck session:
```
2019-05-10 16:21:52
Full thread dump OpenJDK 64-Bit Server VM (11+28 mixed mode):

Threads class SMR info:
_java_thread_list=0x00007fa26a3f4e20, length=15, elements={
0x00007fa269802000, 0x00007fa26b8f8000, 0x00007fa26b8fb000, 0x00007fa269002000,
0x00007fa26b008800, 0x00007fa26b00e800, 0x00007fa26b01b000, 0x00007fa26801d000,
0x00007fa26b925800, 0x00007fa26ba98800, 0x00007fa26b1b2800, 0x00007fa26bb3d800,
0x00007fa26b1a3000, 0x00007fa2699fe000, 0x00007fa26dbdc800
}

"main" #1 prio=5 os_prio=31 cpu=1999.03ms elapsed=62.60s tid=0x00007fa269802000 nid=0x2403 waiting on condition  [0x0000700006df6000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(java.base@11/Native Method)
	at io.typefox.yang.diagram.YangServerLauncher.start(YangServerLauncher.java:211)
	at org.eclipse.xtext.ide.server.ServerLauncher.launch(ServerLauncher.java:54)
	at io.typefox.yang.diagram.YangServerLauncher.main(YangServerLauncher.java:179)

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=12.00ms elapsed=62.58s tid=0x00007fa26b8f8000 nid=0x3303 waiting on condition  [0x000070000750b000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=31 cpu=0.48ms elapsed=62.57s tid=0x00007fa26b8fb000 nid=0x4603 in Object.wait()  [0x000070000760e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11/Native Method)
	- waiting on <0x00000007001a9ce0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x00000007001a9ce0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=0.32ms elapsed=62.56s tid=0x00007fa269002000 nid=0x3903 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 cpu=6478.79ms elapsed=62.56s tid=0x00007fa26b008800 nid=0x3b03 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #8 daemon prio=9 os_prio=31 cpu=2608.60ms elapsed=62.56s tid=0x00007fa26b00e800 nid=0x3d03 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #9 daemon prio=9 os_prio=31 cpu=50.85ms elapsed=62.56s tid=0x00007fa26b01b000 nid=0x5703 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #10 daemon prio=9 os_prio=31 cpu=0.07ms elapsed=62.52s tid=0x00007fa26801d000 nid=0xa703 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #11 daemon prio=8 os_prio=31 cpu=0.95ms elapsed=62.51s tid=0x00007fa26b925800 nid=0x5903 in Object.wait()  [0x0000700007d23000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x00000007001a3df8> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11/Thread.java:834)
	at jdk.internal.misc.InnocuousThread.run(java.base@11/InnocuousThread.java:134)

"EMF Reference Cleaner" #12 daemon prio=5 os_prio=31 cpu=104.66ms elapsed=62.09s tid=0x00007fa26ba98800 nid=0x5e03 in Object.wait()  [0x0000700008335000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11/Native Method)
	- waiting on <no object reference available>
	at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x00000007018ab830> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:176)
	at org.eclipse.emf.common.util.CommonUtil$1ReferenceClearingQueuePollingThread.run(CommonUtil.java:70)

"com.google.inject.internal.util.$Finalizer" #14 daemon prio=5 os_prio=31 cpu=0.13ms elapsed=61.67s tid=0x00007fa26b1b2800 nid=0x6003 in Object.wait()  [0x0000700008438000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11/Native Method)
	- waiting on <0x0000000701877ed8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000701877ed8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11/ReferenceQueue.java:176)
	at com.google.inject.internal.util.$Finalizer.run(Finalizer.java:114)

"AsyncAppender-Dispatcher-Thread-1" #15 daemon prio=5 os_prio=31 cpu=74.73ms elapsed=60.54s tid=0x00007fa26bb3d800 nid=0x9703 in Object.wait()  [0x0000700008844000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@11/Object.java:328)
	at org.apache.log4j.AsyncAppender$Dispatcher.run(AsyncAppender.java:548)
	- waiting to re-lock in wait() <0x00000007018df2d8> (a java.util.ArrayList)
	at java.lang.Thread.run(java.base@11/Thread.java:834)

"pool-4-thread-1" #16 prio=5 os_prio=31 cpu=45.46ms elapsed=60.53s tid=0x00007fa26b1a3000 nid=0x9603 runnable  [0x0000700008947000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(java.base@11/Native Method)
	at java.io.FileInputStream.read(java.base@11/FileInputStream.java:279)
	at java.io.BufferedInputStream.fill(java.base@11/BufferedInputStream.java:252)
	at java.io.BufferedInputStream.read(java.base@11/BufferedInputStream.java:271)
	- locked <0x00000007001a6320> (a java.io.BufferedInputStream)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:75)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:95)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11/Thread.java:834)

"RequestManager-Queue-0" #17 daemon prio=5 os_prio=31 cpu=59818.48ms elapsed=60.48s tid=0x00007fa2699fe000 nid=0x9403 runnable  [0x0000700008a47000]
   java.lang.Thread.State: RUNNABLE
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:568)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:568)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:673)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:568)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:568)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:673)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:568)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:568)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:673)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:568)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:568)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:673)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:568)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:568)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:673)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:568)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:673)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.Iterators.addAll(Iterators.java:364)
	at com.google.common.collect.Lists.newArrayList(Lists.java:162)
	at com.google.common.collect.Lists.newArrayList(Lists.java:146)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toList(IterableExtensions.java:600)
	at io.typefox.yang.scoping.xpath.XpathResolver.findNodes(XpathResolver.java:861)
	at io.typefox.yang.scoping.xpath.XpathResolver.computeType(XpathResolver.java:769)
	at io.typefox.yang.scoping.xpath.XpathResolver.lambda$_internalResolveStep$5(XpathResolver.java:699)
	at io.typefox.yang.scoping.xpath.XpathResolver$$Lambda$256/0x00000008003f6040.apply(Unknown Source)
	at io.typefox.yang.scoping.Linker.link(Linker.java:46)
	at io.typefox.yang.scoping.xpath.XpathResolver._internalResolveStep(XpathResolver.java:703)
	at io.typefox.yang.scoping.xpath.XpathResolver.internalResolveStep(XpathResolver.java:961)
	at io.typefox.yang.scoping.xpath.XpathResolver._internalResolve(XpathResolver.java:374)
	at io.typefox.yang.scoping.xpath.XpathResolver.internalResolve(XpathResolver.java:926)
	at io.typefox.yang.scoping.xpath.XpathResolver.doResolve(XpathResolver.java:306)
	at io.typefox.yang.scoping.ScopeContextProvider.lambda$_computeScope$21(ScopeContextProvider.java:609)
	at io.typefox.yang.scoping.ScopeContextProvider$$Lambda$265/0x00000008003fa040.run(Unknown Source)
	at io.typefox.yang.scoping.ScopeContext.lambda$resolveAll$12(ScopeContext.java:426)
	at io.typefox.yang.scoping.ScopeContext$$Lambda$158/0x000000080039bc40.accept(Unknown Source)
	at java.util.ArrayList.forEach(java.base@11/ArrayList.java:1540)
	at io.typefox.yang.scoping.ScopeContext.resolveAll(ScopeContext.java:428)
	at io.typefox.yang.resource.YangResource.getEObject(YangResource.java:39)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:222)
	- locked <0x0000000701a94730> (a io.typefox.yang.resource.YangResource)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doResolveLazyCrossReference(LazyLinkingResource.java:189)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.resolveLazyCrossReference(LazyLinkingResource.java:148)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.resolveLazyCrossReferences(LazyLinkingResource.java:134)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:500)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.lambda$launch$6(IncrementalBuilder.java:237)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder$$Lambda$138/0x0000000800399040.apply(Unknown Source)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.lambda$executeClustered$1(ClusteringStorageAwareResourceLoader.java:77)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader$$Lambda$129/0x0000000800382c40.apply(Unknown Source)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:640)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at java.util.AbstractCollection.toArray(java.base@11/AbstractCollection.java:144)
	at java.util.ArrayList.addAll(java.base@11/ArrayList.java:701)
	at com.google.common.collect.Iterables.addAll(Iterables.java:350)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:80)
	at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:55)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:252)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:400)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:385)
	at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:115)
	at org.eclipse.xtext.ide.server.ProjectManager.doInitialBuild(ProjectManager.java:107)
	at org.eclipse.xtext.ide.server.BuildManager.doInitialBuild(BuildManager.java:149)
	at org.eclipse.xtext.ide.server.WorkspaceManager.refreshWorkspaceConfig(WorkspaceManager.java:148)
	at org.eclipse.xtext.ide.server.WorkspaceManager.initialize(WorkspaceManager.java:117)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$initialize$10(LanguageServerImpl.java:295)
	at org.eclipse.xtext.ide.server.LanguageServerImpl$$Lambda$97/0x000000080033b440.apply(Unknown Source)
	at org.eclipse.xtext.ide.server.concurrent.WriteRequest.run(WriteRequest.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@11/Executors.java:515)
	at java.util.concurrent.FutureTask.run(java.base@11/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11/ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11/Thread.java:834)

"Attach Listener" #18 daemon prio=9 os_prio=31 cpu=1.05ms elapsed=0.10s tid=0x00007fa26dbdc800 nid=0x6307 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=31 cpu=40.11ms elapsed=62.58s tid=0x00007fa26b8f4800 nid=0x3203 runnable

"GC Thread#0" os_prio=31 cpu=164.40ms elapsed=62.60s tid=0x00007fa268807800 nid=0x2e03 runnable

"GC Thread#1" os_prio=31 cpu=184.61ms elapsed=62.10s tid=0x00007fa26c050000 nid=0x5a03 runnable

"GC Thread#2" os_prio=31 cpu=177.90ms elapsed=62.10s tid=0x00007fa26c051000 nid=0x5b03 runnable

"GC Thread#3" os_prio=31 cpu=173.14ms elapsed=62.10s tid=0x00007fa26c061800 nid=0x5d03 runnable

"GC Thread#4" os_prio=31 cpu=190.59ms elapsed=62.10s tid=0x00007fa269801000 nid=0xa003 runnable

"GC Thread#5" os_prio=31 cpu=185.72ms elapsed=62.10s tid=0x00007fa268905000 nid=0x9e03 runnable

"GC Thread#6" os_prio=31 cpu=105.76ms elapsed=57.25s tid=0x00007fa26bebf000 nid=0x7003 runnable

"GC Thread#7" os_prio=31 cpu=48.37ms elapsed=52.96s tid=0x00007fa26d314000 nid=0x6107 runnable

"G1 Main Marker" os_prio=31 cpu=0.71ms elapsed=62.60s tid=0x00007fa26b835800 nid=0x5003 runnable

"G1 Conc#0" os_prio=31 cpu=6.73ms elapsed=62.60s tid=0x00007fa26b836800 nid=0x4e03 runnable

"G1 Conc#1" os_prio=31 cpu=6.60ms elapsed=61.13s tid=0x00007fa26b05e800 nid=0x6503 runnable

"G1 Refine#0" os_prio=31 cpu=56.22ms elapsed=62.60s tid=0x00007fa26b8d7000 nid=0x4c03 runnable

"G1 Refine#1" os_prio=31 cpu=27.18ms elapsed=58.67s tid=0x00007fa26c1f2800 nid=0x6c03 runnable

"G1 Refine#2" os_prio=31 cpu=20.04ms elapsed=58.67s tid=0x00007fa26c366800 nid=0x6e03 runnable

"G1 Refine#3" os_prio=31 cpu=12.23ms elapsed=58.67s tid=0x00007fa26918f000 nid=0x6f03 runnable

"G1 Refine#4" os_prio=31 cpu=7.60ms elapsed=57.24s tid=0x00007fa268ba7800 nid=0x7103 runnable

"G1 Refine#5" os_prio=31 cpu=2.93ms elapsed=57.24s tid=0x00007fa26c143000 nid=0x7303 runnable

"G1 Refine#6" os_prio=31 cpu=0.82ms elapsed=57.24s tid=0x00007fa26c141000 nid=0x8f03 runnable

"G1 Young RemSet Sampling" os_prio=31 cpu=18.71ms elapsed=62.60s tid=0x00007fa26b8d8000 nid=0x4a03 runnable
"VM Periodic Task Thread" os_prio=31 cpu=33.89ms elapsed=62.52s tid=0x00007fa26b8f3000 nid=0xa503 waiting on condition

JNI global refs: 10, weak refs: 0
```

I'm also seeing the following in the window log, but it's not clear this is caused by the YANG extension: 

```
[2019-05-10 16:19:00.503] [renderer1] [error] Channel has been closed: Error: Channel has been closed
	at f.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:630:195)
	at f.appendLine (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:629:908)
	at define.createOutputChannel.appendLine.t.then.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:631:908)
```
